<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Modules.Argus.Domain\Modules.Argus.Domain.csproj" />
    <ProjectReference Include="..\Modules.Argus.Application\Modules.Argus.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
  <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>

<ItemGroup>
  <None Remove="Knowledge\argus-knowledge.hu.json" />

  <Content Include="Knowledge\argus-knowledge.hu.json">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <TargetPath>Knowledge\argus-knowledge.hu.json</TargetPath>
  </Content>
</ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
