@WebApi_HostAddress = http://localhost:5270

POST {{WebApi_HostAddress}}/api/admin/artworks
Content-Type: application/json
Accept: application/json

{
  "titleHu": "Táj",
  "titleEn": "Landscape",
  "year": 2024,
  "techniqueHu": "olaj, vászon",
  "techniqueEn": "oil on canvas",
  "widthCm": 80,
  "heightCm": 60
}

###

POST {{WebApi_HostAddress}}/api/admin/artworks
Content-Type: application/json
Accept: application/json

{
  "titleHu": "",
  "year": 9999,
  "widthCm": -10,
  "heightCm": 0
}

###

GET {{WebApi_HostAddress}}/api/artworks
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/admin/files
Content-Type: multipart/form-data; boundary=FileBoundary
Accept: application/json

--FileBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< ./TestFiles/test.jpg
--FileBoundary--

######

GET {{WebApi_HostAddress}}/api/admin/files/27139e0b-9c50-4457-9fb1-6059ff0ff502

###

PUT {{WebApi_HostAddress}}/api/admin/artworks/b4ba4b50-63e6-42b7-83e1-1146e72263a6/image
Content-Type: application/json

{
  "fileId": "27139e0b-9c50-4457-9fb1-6059ff0ff502"
}

###

PUT {{WebApi_HostAddress}}/api/admin/artworks/b4ba4b50-63e6-42b7-83e1-1146e72263a6/publish
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/artworks/b4ba4b50-63e6-42b7-83e1-1146e72263a6/image
Accept: image/*