@WebApi_HostAddress = http://localhost:5270

POST {{WebApi_HostAddress}}/api/admin/artworks
Content-Type: application/json
Accept: application/json

{
  "titleHu": "Táj",
  "titleEn": "Landscape",
  "year": 2024,
  "techniqueHu": "olaj, vászon",
  "techniqueEn": "oil on canvas",
  "widthCm": 80,
  "heightCm": 60
}

###

POST {{WebApi_HostAddress}}/api/admin/artworks
Content-Type: application/json
Accept: application/json

{
  "titleHu": "",
  "year": 9999,
  "widthCm": -10,
  "heightCm": 0
}

###

GET {{WebApi_HostAddress}}/api/artworks
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/admin/files
Content-Type: multipart/form-data; boundary=FileBoundary
Accept: application/json

--FileBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< ./TestFiles/test.jpg
--FileBoundary--

######

GET {{WebApi_HostAddress}}/api/admin/files/27139e0b-9c50-4457-9fb1-6059ff0ff502

###

PUT {{WebApi_HostAddress}}/api/admin/artworks/b4ba4b50-63e6-42b7-83e1-1146e72263a6/image
Content-Type: application/json

{
  "fileId": "27139e0b-9c50-4457-9fb1-6059ff0ff502"
}

###

PUT {{WebApi_HostAddress}}/api/admin/artworks/b4ba4b50-63e6-42b7-83e1-1146e72263a6/publish
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/artworks/b4ba4b50-63e6-42b7-83e1-1146e72263a6/image
Accept: image/*

###

GET {{WebApi_HostAddress}}/api/artworks
Accept: application/json

###

PUT {{WebApi_HostAddress}}/api/admin/artworks/a4ba4b50-63e6-42b7-83e1-1146e72263a6/publish
Accept: application/json

### Publikált mű adatlapja

@artworkId = b4ba4b50-63e6-42b7-83e1-1146e72263a5

GET {{WebApi_HostAddress}}/api/artworks/{{artworkId}}
Accept: application/json

### Admin műlista

GET {{WebApi_HostAddress}}/api/admin/artworks
Accept: application/json

### Delete Artwork

DELETE {{WebApi_HostAddress}}/api/admin/artworks/71280310-89b6-425d-8bfd-227cd3a942f0
Accept: application/json

### Mű adatainak módosítása

PUT {{WebApi_HostAddress}}/api/admin/artworks/b621f34b-80ce-40fc-a8ae-9e86dcba3e4a
Content-Type: application/json
Accept: application/json

{
  "titleHu": "Lélek-táj",
  "titleEn": "Soul Landscape",
  "year": 2025,
  "techniqueHu": "olaj, vászon",
  "techniqueEn": "oil on canvas",
  "widthCm": 80,
  "heightCm": 60,
  "descriptionHu": "A mű magyar nyelvű leírása.",
  "descriptionEn": "English description of the artwork.",
  "isFeatured": false,
  "displayOrder": 1
}

### Admin mű részletei

GET {{WebApi_HostAddress}}/api/admin/artworks/b621f34b-80ce-40fc-a8ae-9e86dcba3e4a
Accept: application/json

### Publikáció visszavonása

PUT {{WebApi_HostAddress}}/api/admin/artworks/b4ba4b50-63e6-42b7-83e1-1146e72263a6/unpublish
Accept: application/json

### Mű publikálása

PUT {{WebApi_HostAddress}}/api/admin/artworks/b4ba4b50-63e6-42b7-83e1-1146e72263a6/publish
Accept: application/json

### 1. Meghívóvázlat létrehozása
# @name createInvitation

POST {{WebApi_HostAddress}}/api/admin/invitations
Content-Type: application/json
Accept: application/json

{
  "titleHu": "Tesztmeghívó",
  "titleEn": "Test invitation",
  "year": 2026,
  "altTextHu": "A tesztmeghívó képe",
  "altTextEn": "Image of the test invitation",
  "displayOrder": 0
}

### 2. Képfájl feltöltése
# @name uploadInvitationImage

POST {{WebApi_HostAddress}}/api/admin/files
Content-Type: multipart/form-data; boundary=InvitationBoundary
Accept: application/json

--InvitationBoundary
Content-Disposition: form-data; name="file"; filename="invitation.jpg"
Content-Type: image/jpeg

< ./TestFiles/invitation.jpg
--InvitationBoundary--

### 3. Feltöltött kép csatolása a meghívóhoz

PUT {{WebApi_HostAddress}}/api/admin/invitations/03f88412-2117-4114-a9a2-40035c937a8e/image
Content-Type: application/json
Accept: application/json

{
  "fileId": "2d6deaf6-92e3-4006-b169-ad76f5fd6c35"
}

### Meghívó publikálása

PUT {{WebApi_HostAddress}}/api/admin/invitations/03f88412-2117-4114-a9a2-40035c937a8e/publish
Accept: application/json

### Publikus meghívólista

GET {{WebApi_HostAddress}}/api/invitations
Accept: application/json

### Publikus meghívókép

GET {{WebApi_HostAddress}}/api/invitations/03f88412-2117-4114-a9a2-40035c937a8e/image
Accept: image/*

### Admin meghívólista

GET {{WebApi_HostAddress}}/api/admin/invitations
Accept: application/json

### Admin meghívókép

GET {{WebApi_HostAddress}}/api/admin/invitations/03f88412-2117-4114-a9a2-40035c937a8e/image
Accept: image/*

### Meghívó visszavonása

PUT {{WebApi_HostAddress}}/api/admin/invitations/03f88412-2117-4114-a9a2-40035c937a8e/unpublish
Accept: application/json

### Admin meghívó részletei

GET {{WebApi_HostAddress}}/api/admin/invitations/03f88412-2117-4114-a9a2-40035c937a8e
Accept: application/json

### Meghívó adatainak módosítása

PUT {{WebApi_HostAddress}}/api/admin/invitations/03f88412-2117-4114-a9a2-40035c937a8e
Content-Type: application/json
Accept: application/json

{
  "titleHu": "Módosított tesztmeghívó",
  "titleEn": "Updated test invitation",
  "year": 2026,
  "altTextHu": "A módosított meghívó képe",
  "altTextEn": "Image of the updated invitation",
  "displayOrder": 1
}

### Meghívó törlése

DELETE {{WebApi_HostAddress}}/api/admin/invitations/03f88412-2117-4114-a9a2-40035c937a8e
Accept: application/json

### Kiállítások oldal létrehozása vagy frissítése

PUT {{WebApi_HostAddress}}/api/admin/content-pages/exhibitions
Content-Type: application/json
Accept: application/json

{
  "titleHu": "Kiállítások",
  "titleEn": "Exhibitions",
  "contentHu": "## Egyéni kiállítások\n\n- 2025 Berlin, Art at Berlin\n- 2022 Edinburgh, Contemporary Art Studios\n\n## Csoportos kiállítások\n\n- 2024 Szeged\n- 2023 Budapest",
  "contentEn": "## Solo exhibitions\n\n- 2025 Berlin, Art at Berlin\n- 2022 Edinburgh, Contemporary Art Studios\n\n## Group exhibitions\n\n- 2024 Szeged\n- 2023 Budapest"
}


### Admin tartalmi oldal lekérése kulcs alapján

GET {{WebApi_HostAddress}}/api/admin/content-pages/exhibitions
Accept: application/json

### Admin tartalmi oldal publikálása

PUT {{WebApi_HostAddress}}/api/admin/content-pages/exhibitions/publish
Accept: application/json

### Publikálás visszavonása

PUT {{WebApi_HostAddress}}/api/admin/content-pages/exhibitions/unpublish
Accept: application/json

### Publikus tartalmi oldal lekérése kulcs alapján

GET {{WebApi_HostAddress}}/api/content-pages/exhibitions
Accept: application/json

### Admin tartalmi oldalak listája

GET {{WebApi_HostAddress}}/api/admin/content-pages
Accept: application/json

### Tagságok és díjak létrehozása

PUT {{WebApi_HostAddress}}/api/admin/content-pages/memberships-and-awards
Content-Type: application/json

{
  "titleHu": "Tagságok és díjak",
  "titleEn": "Memberships and awards",
  "contentHu": "A tartalom szerkesztés alatt.",
  "contentEn": "Content is being edited."
}

### Írások létrehozása

PUT {{WebApi_HostAddress}}/api/admin/content-pages/writings
Content-Type: application/json

{
  "titleHu": "Írások",
  "titleEn": "Writings",
  "contentHu": "A tartalom szerkesztés alatt.",
  "contentEn": "Content is being edited."
}

### Írás létrehozása

POST {{WebApi_HostAddress}}/api/admin/articles
Content-Type: application/json
Accept: application/json

{
  "slug": "fodor-jozsef-megnyito-beszede-2002",
  "titleHu": "Fodor József megnyitóbeszéde",
  "titleEn": null,
  "summaryHu": "2002. március 13., Hódmezővásárhely – megnyitóbeszéd",
  "summaryEn": null,
  "contentHu": "<h2>Kapuk, angyalok, városok</h2><p>Ez egy rövid próbatartalom.</p><blockquote>A szín a lélek skálája.</blockquote>",
  "contentEn": null,
  "displayOrder": 0
}

@articleId = f35ffda3-de73-472e-a474-aa933a216c56

### Írás publikálása

PUT {{WebApi_HostAddress}}/api/admin/articles/{{articleId}}/publish
Accept: application/json

### Publikálás visszavonása

PUT {{WebApi_HostAddress}}/api/admin/articles/{{articleId}}/unpublish
Accept: application/json

### Publikus írások listája

GET {{WebApi_HostAddress}}/api/articles
Accept: application/json

### Publikus írás lekérése slug alapján

GET {{WebApi_HostAddress}}/api/articles/fodor-jozsef-megnyito-beszede-2002
Accept: application/json

### Admin írások listája

GET {{WebApi_HostAddress}}/api/admin/articles
Accept: application/json


@articleId = f35ffda3-de73-472e-a474-aa933a216c56

### Írás admin részletei

GET {{WebApi_HostAddress}}/api/admin/articles/{{articleId}}
Accept: application/json


@articleId = f35ffda3-de73-472e-a474-aa933a216c56

### Írás módosítása

PUT {{WebApi_HostAddress}}/api/admin/articles/{{articleId}}
Content-Type: application/json
Accept: application/json

{
  "titleHu": "Fodor József megnyitóbeszéde",
  "titleEn": "Opening speech by József Fodor",
  "summaryHu": "2002. március 13., Hódmezővásárhely – megnyitóbeszéd",
  "summaryEn": "13 March 2002, Hódmezővásárhely – opening speech",
  "contentHu": "<h2>Kapuk, angyalok, városok</h2><p>A módosított próbatartalom.</p><blockquote>A szín a lélek skálája.</blockquote>",
  "contentEn": null,
  "displayOrder": 1
}